%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\Dropbox\Refsum\manuscript\supplementary tables\ST1_peroxisomalFix.xlsx
%    Worksheet: HAM'sF10
%
% Auto-generated by MATLAB on 13-Mar-2019 09:19:04

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 15);

% Specify sheet and range
opts.Sheet = "HAM'sF10";
opts.DataRange = "A2:O71";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "ModelMetIDs", "Var13", "lb", "ub"];
opts.SelectedVariableNames = ["ModelMetIDs", "lb", "ub"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "double", "double"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("E:\Dropbox\Refsum\manuscript\supplementary tables\ST1_peroxisomalFix.xlsx", opts, "UseExcel", false);

%% Convert to output type
ModelMetIDs = tbl.ModelMetIDs;
lb = tbl.lb;
ub = tbl.ub;

%% Clear temporary variables
clear opts tbl