%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\Dropbox\Refsum\manuscript\supplementary tables\ST2_fibroblast.xlsx
%    Worksheet: Summary
%
% Auto-generated by MATLAB on 13-Mar-2019 09:21:21

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 17);

% Specify sheet and range
opts.Sheet = "Summary";
opts.DataRange = "A3:Q1679";

% Specify column names and types
opts.VariableNames = ["EntrezID", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "DECISION"];
opts.SelectedVariableNames = ["EntrezID", "DECISION"];
opts.VariableTypes = ["double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "double"];
opts = setvaropts(opts, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("E:\Dropbox\Refsum\manuscript\supplementary tables\ST2_fibroblast.xlsx", opts, "UseExcel", false);

%% Convert to output type
EntrezID = tbl.EntrezID;
DECISION = tbl.DECISION;

%% Clear temporary variables
clear opts tbl

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = "CoreActiveRxns";
opts.DataRange = "A2:A134";

% Specify column names and types
opts.VariableNames = "ActiveRxns";
opts.SelectedVariableNames = "ActiveRxns";
opts.VariableTypes = "string";
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("E:\Dropbox\Refsum\manuscript\supplementary tables\ST2_fibroblast.xlsx", opts, "UseExcel", false);

%% Convert to output type
ActiveRxns = tbl.ActiveRxns;

%% Clear temporary variables
clear opts tbl
